pkgs:
let
  lib = pkgs.lib;

  defaultExcludes = [
    # Generated lock files
    "*.lock"
    "Cargo.lock"

    # Files generated by patch
    "*.patch"

    # NPM
    "package-lock.json"

    # VCS
    ".gitignore"
    ".gitmodules"

    # Build artifacts
    "target/*"
    "result"
    "result-*"

    # Nix build results
    ".direnv"
  ];

  copyrightFiles = [ "*.rs" ];

  treefmtConfig = pkgs.treefmt.buildConfig {
    on-unmatched = "debug";
    excludes = defaultExcludes;

    formatter = {
      # Copyright headers (runs first - priority 1)
      copyright = {
        command = lib.getExe pkgs.addlicense;
        options = [
          "-f"
          ./fmt-assets/copyright.tpl
          "-ignore"
          "**/Cargo.lock"
          "-ignore"
          "**/target/**"
        ];
        includes = copyrightFiles;
        priority = 1;
      };

      # Rust formatting (runs after copyright - priority 2)
      rust = {
        command = lib.getExe pkgs.rustfmt;
        options = [ "--edition" "2024" ];
        includes = [ "*.rs" ];
        priority = 2;
      };

      # Nix formatting
      nix = {
        command = lib.getExe pkgs.nixpkgs-fmt;
        includes = [ "*.nix" ];
        priority = 3;
      };

      # Shell script formatting
      shell = {
        command = lib.getExe pkgs.shfmt;
        options = [ "--simplify" "--write" "--binary-next-line" "--indent" "2" ];
        includes = [ "*.sh" "*.bash" ];
        priority = 3;
      };

      # TOML formatting
      toml = {
        command = lib.getExe pkgs.taplo;
        options = [ "format" ];
        includes = [ "*.toml" ];
        priority = 3;
      };

      # Markdown formatting
      markdown = {
        command = lib.getExe pkgs.mdformat;
        options = [ "--number" "--wrap" "100" ];
        includes = [ "*.md" ];
        priority = 3;
      };
    };
  };
in
pkgs.writeShellApplication {
  name = "fluxion-fmt";
  runtimeInputs = with pkgs; [ gitMinimal ];
  text = ''
    args=("$@")

    if tree_root=$(git rev-parse --show-toplevel 2>/dev/null); then
      walk="git"
    else
      walk="filesystem"
      tree_root="."
    fi

    echo "🎨 FluxION Formatter"
    echo "   Root: $tree_root ($walk)"
    echo "   License: CC-BY-NC-ND-4.0 (SOLARE S.R.O.)"
    echo ""

    exec ${pkgs.treefmt}/bin/treefmt \
      --config-file ${treefmtConfig} \
      --tree-root "$tree_root" \
      --walk "$walk" \
      "''${args[@]}"
  '';
}
