// Copyright (c) 2025 SOLARE S.R.O.
//
// This file is part of FluxION.
//
// FluxION is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// FluxION is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with FluxION. If not, see <https://www.gnu.org/licenses/>.
//
// For commercial licensing, please contact: info@solare.cz

//! Per-strategy statistics and performance metrics

use serde::{Deserialize, Serialize};

/// Internal metrics collector for a strategy
#[derive(Debug, Clone)]
pub struct StrategyMetrics {
    pub total_blocks: usize,
    pub total_profit_czk: f32,
    pub total_charge_kwh: f32,
    pub total_discharge_kwh: f32,
    pub profitable_blocks: usize,
}

impl StrategyMetrics {
    pub fn new() -> Self {
        Self {
            total_blocks: 0,
            total_profit_czk: 0.0,
            total_charge_kwh: 0.0,
            total_discharge_kwh: 0.0,
            profitable_blocks: 0,
        }
    }
}

/// Statistics for a single strategy's performance
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyStatistics {
    /// Name of the strategy
    pub strategy_name: String,

    /// Total number of blocks this strategy was used
    pub total_blocks: usize,

    /// Win rate (% of total blocks this strategy was chosen)
    pub win_rate_percent: f32,

    /// Total profit generated by this strategy (CZK)
    pub total_profit_czk: f32,

    /// Average profit per block (CZK)
    pub average_profit_per_block: f32,

    /// Number of blocks where this strategy was profitable
    pub profitable_blocks: usize,

    /// Profit rate (% of blocks that were profitable)
    pub profit_rate_percent: f32,

    /// Total energy charged when using this strategy (kWh)
    pub total_charge_kwh: f32,

    /// Total energy discharged when using this strategy (kWh)
    pub total_discharge_kwh: f32,
}

impl StrategyStatistics {
    /// Calculate contribution to total profit
    pub fn profit_contribution_percent(&self, total_profit: f32) -> f32 {
        if total_profit == 0.0 {
            return 0.0;
        }
        (self.total_profit_czk / total_profit) * 100.0
    }

    /// Get performance rating based on various factors
    /// Returns a score from 0-100
    pub fn performance_score(&self) -> f32 {
        // Weighted score:
        // - 40% profit rate (how often profitable)
        // - 30% average profit per block
        // - 30% win rate (how often used)

        let profit_rate_score = self.profit_rate_percent * 0.4;
        let avg_profit_score = if self.average_profit_per_block > 0.0 {
            (self.average_profit_per_block / 0.1).min(100.0) * 0.3 // Normalize assuming 0.1 CZK is good
        } else {
            0.0
        };
        let win_rate_score = self.win_rate_percent * 0.3;

        profit_rate_score + avg_profit_score + win_rate_score
    }

    /// Get strategy grade (A-F) based on performance
    pub fn strategy_grade(&self) -> char {
        let score = self.performance_score();

        if score >= 80.0 {
            'A'
        } else if score >= 70.0 {
            'B'
        } else if score >= 60.0 {
            'C'
        } else if score >= 50.0 {
            'D'
        } else if score >= 40.0 {
            'E'
        } else {
            'F'
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_profit_contribution() {
        let stats = StrategyStatistics {
            strategy_name: "Test".to_string(),
            total_blocks: 100,
            win_rate_percent: 50.0,
            total_profit_czk: 250.0,
            average_profit_per_block: 2.5,
            profitable_blocks: 80,
            profit_rate_percent: 80.0,
            total_charge_kwh: 50.0,
            total_discharge_kwh: 48.0,
        };

        assert_eq!(stats.profit_contribution_percent(1000.0), 25.0);
    }

    #[test]
    fn test_performance_score() {
        let stats = StrategyStatistics {
            strategy_name: "Test".to_string(),
            total_blocks: 100,
            win_rate_percent: 50.0,
            total_profit_czk: 250.0,
            average_profit_per_block: 0.15,
            profitable_blocks: 90,
            profit_rate_percent: 90.0,
            total_charge_kwh: 50.0,
            total_discharge_kwh: 48.0,
        };

        // Score = 90% * 0.4 + (0.15/0.1) * 0.3 + 50% * 0.3
        // = 36.0 + 45.0 + 15.0 = 96.0
        let score = stats.performance_score();
        assert!((score - 96.0).abs() < 1.0);
    }

    #[test]
    fn test_strategy_grade() {
        let mut stats = StrategyStatistics {
            strategy_name: "Test".to_string(),
            total_blocks: 100,
            win_rate_percent: 50.0,
            total_profit_czk: 250.0,
            average_profit_per_block: 0.15,
            profitable_blocks: 90,
            profit_rate_percent: 90.0,
            total_charge_kwh: 50.0,
            total_discharge_kwh: 48.0,
        };

        assert_eq!(stats.strategy_grade(), 'A');

        stats.profit_rate_percent = 30.0;
        stats.average_profit_per_block = 0.01;
        assert!(stats.strategy_grade() >= 'D');
    }
}
